// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: feed_follows.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedFollowByID = `-- name: GetFeedFollowByID :one
SELECT id, created_at, updated_at, user_id, feed_id FROM feed_follows WHERE feed_id = $1
`

func (q *Queries) GetFeedFollowByID(ctx context.Context, feedID uuid.UUID) (FeedFollow, error) {
	row := q.db.QueryRowContext(ctx, getFeedFollowByID, feedID)
	var i FeedFollow
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.UserID,
		&i.FeedID,
	)
	return i, err
}
